# Analytical approach

## General Model Structure

he available data do not support quantitative catch-at-age modeling for either individual species of octopus in the BSAI or for the multi-species complex, and reliable biomass estimates are unavailable for Tier 5 methods. 
Therefore, we continue to use the alternative Tier 6 method, based on a predation-based estimate of total natural mortality (N), **(reference the SAFE this was first used)**.

The 2011 BSAI octopus assessment introduced the methodology for examining population trends in octopus that is used **(reference 2011 SAFE)**. 
This approach uses the underlying model from Tier 5, where MSY is obtained at ½ the total natural mortality (in tons). 
For Tier 5 stocks, the total natural mortality is usually estimated as the product of biomass (*B*) and an instantaneous mortality rate (*M*), $N=MB$. 
We use the letter *N* for the total natural mortality in tons to distinguish it from the *M* (continuous individual mortality rate) that is used widely in other stock assessment models. 
This method uses data from the AFSC’s food habits database to estimate the total amount of octopus consumed by their main predator in the BSAI: Pacific cod. 
Because Pacific cod is an important commercial species, the AFSC food habits group collects a large number of Pacific cod stomachs for diet analysis. 
The amount of octopus consumed by Pacific cod is a conservative estimate of the total natural mortality *N* for octopus, since it does not include mortality from other predators (i.e., marine mammals) or non-predation mortality. 
**THis published?? This novel approach for setting annual catch limits for data-poor prey species has been presented at scientific conferences and is expected to be published next year**. 
This analysis was originally performed in 2011 using stomach data through 2008 [@Conners2011]. 
The consumption estimator was updated for the 2016 assessment [@Conners2016], and is again updated for this assessment with data through **2022**.


## Parameter Estimates

The consumption estimator was updated in 2023 to include additional samples **(Table 22.6)**. 
The methodology used for this updated estimate is the same as used previously. 
The total consumption of octopus (t/year) estimated for the EBS is shown in **Figure 22.6**. 
We used the geometric mean of the posterior distribution to estimate annual predation for each year in the time series because the posterior distribution is right-skewed (higher values have higher uncertainty). 
Uncertainty of each annual estimate obtained by bootstrapping is also shown. 
Estimates of annual predation mortality by Bering Sea cod on octopus range from <200 to over 20,000 tons; the larger values have a higher level of uncertainty. 
The majority of the annual estimates prior to 2004 are in the range of 3,000 to 6,000 tons. 
The estimates for 2005 – 2015, however, show much higher levels of consumption, with several years in the 10,000-20,000 t range. 
This upward trend was initially assumed to be due to increasing abundance of Pacific cod, but there has also been an increase in the proportion of octopus in the diet of cod **(Figure 22.7)**. 
Over the entire time series, this proportion shows large year-to-year variability and some periods of high consumption for several years followed by low consumption. 
Thus, it is unclear whether the recent upward trend is a permanent change (perhaps due to climate factors) or the peak of a periodic cycle.

We use a geometric mean of all the annual values to calculate a conservative long-term average predation rate over the 30 years of annual estimates. 
The use of the geometric mean is recommended because the distribution of the annual estimates is strongly right-skewed, with annual variance increasing in proportion to the annual mean. 
The geometric mean of all of the annual estimates in the updated data set is 4,770 tons, a substantial increase over the old estimate of 3,452 tons. 
Both estimates are a full order of magnitude higher than the current rate of fishery catch of octopus. 
The BSAI Plan Team requested clarification in September 2016 on whether the arithmetic mean, geometric mean, harmonic mean, or median of the annual values should be used to calculate the long-term average. 
These different approaches are shown in **Table 22.7**. 
At the November 2016 plan team meetings, use of the geometric mean was agreed upon.




