# Results

## Harvest Recommendations

*Amendment 56 Reference Points* \
In previous assessments, catch limits for the octopus stock complex were set using Tier 6 methods based on the maximum historical incidental catch rate. Beginning in 2012, an alternative Tier 6 method based on predation-based estimate of total natural mortality (*N*) was adopted that is based on biological reference points derived from octopus consumption estimates from Pacific cod. This estimate of natural mortality (*N*) can then be combined with the general logistic fisheries model that forms the basis of Tier 5 assessments [@AlversonandPereyra1969; @Francis1974] (Alverson and Petreyra 1969, Francis 1974). Thus, the overfishing limit is set equal to *N*, and the recommended maximum permissible ABC for the octopus stock complex is defined to occur at a harvest rate of 0.75 * OFL.  to set OFL = *N* and ABC = 0.75 * OFL. 

*Specification of OFL and Maximum Permissible ABC* \
**Using the modified Tier 6 methodology, the resulting catch limits are OFL = `r format(OFL_val, big.mark=",")` t and ABC = `r format(round(OFL_val*0.75), big.mark=",")` t which are our recommended `r year+1` and `r year + 2` ABCs and OFLs.**

We do not recommend a directed fishery for octopus in federal waters at this time, because data are insufficient for adequate management. We anticipate that octopus catch in federal waters of the BSAI will continue to be largely incidental catch in existing groundfish fisheries.

*Status Determination* \
The BSAI octopus complex is not currently subject to overfishing because the `r year-1` catch, the most recent completed year, of `r format(round(prior_cat), big.mark=",")` t is smaller than the `r year-1` OFL of `r format(round(prior_OFL), big.mark=",")` t (Figure `r params$chapter`-\@ref(fig:fig-catch)). 

